name: service-template-go-two
author: ase-dev
source: https://github.com/vu-ase/imaging
version: 1.0.1
description: Write a Rover service in Go

commands:
  build: make build
  run: ./bin/SERVICE_NAME

inputs:
  - service: example-input
    streams:
      - rpm-data
outputs:
  - example-output

configuration:
  - name: number-example
    type: number
    value: 30
  - name: string-example
    type: string
    value: "hello all"
  - name: tunable-string-example
    type: string
    value: "hello all, this is tunable"
    tunable: true